# Generated by Django 6.0.1 on 2026-03-02 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(
                validators=[django.core.validators.
                            MinLengthValidator(256)]
            ),
        ),
    ]
