# Generated by Django 6.0.1 on 2026-03-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_recipe_author_recipeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='task_image',
            new_name='recipe_image',
        ),
    ]
